services:
  - type: worker
    name: vanity-sniper
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_USER_TOKEN
        sync: false
      - key: DISCORD_PASSWORD
        sync: false
      - key: DISCORD_TOTP_SECRET
        sync: false
      - key: GUILD_ID
        sync: false
      - key: VANITY_CODE
        value: gvrn
      - key: NOTIFY_CHANNEL_ID
        value: "1526835509253636210"
      - key: NOTIFY_GUILD_ID
        sync: false
      - key: PING_USER_ID
        value: "1524709993499197443"
      - key: PING_COUNT
        value: "100"
      - key: INTERVAL_MINUTES
        value: "1"
