services:
  - type: worker
    name: vanity-sniper
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_USER_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: VANITY_CODE
        value: gvrn
      - key: NOTIFY_CHANNEL_ID
        value: "1526835509253636210"
      - key: INTERVAL_MINUTES
        value: "1"
